[package]
name = "split-purikura"
version = "0.1.5"
edition = "2021"

[[bin]]
name = "プリプリメーカー"
path = "src/main.rs"

[dependencies]
iced = { version = "0.13.1", features = ["image"] }
image = "0.25.5"

[build-dependencies]
winresource = "0.1"